language: go

sudo: required

services:
  - docker

go:
    - 1.5
    - 1.6
    - 1.7

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
    - curl https://raw.githubusercontent.com/opalmer/docker-gerrittest/master/helper-functions.sh -o helper-functions.sh

script:
    - . helper-functions.sh
    - $HOME/gopath/bin/goveralls -service=travis-ci
