language: go

sudo: required

services:
  - docker

go:
    - 1.5
    - 1.6
    - 1.7

before_install:
    - go get github.com/axw/gocov/gocov
    - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
    - go get -t -v ./...
    - ./.ci/travis/start-gerrit.sh

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
