version: '2'

services:
  # A simple reverse-proxy written in Go
  # that's used to control authentication.
  http:
    build: http
    ports:
      - "8088:8088"
    links:
      - gerrit

  postgres:
    image: postgres:9.5.3
    environment:
      - POSTGRES_DB=reviewdb
      - POSTGRES_USER=gerrit2
      - POSTGRES_PASSWORD=gerrit

  gerrit:
    build: gerrit
    ports:
      - "29418:29418"
    links:
      - postgres
