version: '2'

services:
  # A simple reverse-proxy written in Go
  # that's used to control authentication.
  http:
    build: http
    container_name: gerrit_http
    ports:
      - "8088:8088"
    links:
      - gerrit

  postgres:
    image: postgres:9.5.3
    container_name: gerrit_db
    env_file: postgres/environment.env

  gerrit:
    build: gerrit
    container_name: gerrit
    ports:
      - "29418:29418"
    links:
      - postgres
