version: '2'

services:
  nginx:
    build: nginx
    ports:
      - "8888:8888"
    links:
      - gerrit

  postgres:
    image: postgres:9.5.3
    environment:
      - POSTGRES_DB=reviewdb
      - POSTGRES_USER=gerrit2
      - POSTGRES_PASSWORD=gerrit

  gerrit:
    build: gerrit
    ports:
      - "29418:29418"
    links:
      - postgres
